#!/bin/sh
mkdir /var/log/tinyproxy/ -p
echo "Start" >> /var/log/tinyproxy/tinyproxy.log
while true
do
aaa=0   
aaa=`cat /var/log/tinyproxy/tinyproxy.log | grep Interrupted | grep -v "grep"| wc -l |awk '{print $1}'`
if [ $aaa -ne 0 ] 
then    
rm -rf /var/log/tinyproxy/tinyproxy.log
pkill tinyproxy
service tinyproxy restart 
fi
pkill vpncmd
/usr/sbin/VPNAnalyse &
sleep 15
IPAddress=`wget http://members.3322.org/dyndns/getip -O - -q ; echo`
echo "http-proxy $IPAddress 80" > /var/www/html/163-CUC.ovpn
echo "http-proxy $IPAddress 80" > /var/www/html/163-CTC.ovpn
echo "http-proxy $IPAddress 80" > /var/www/html/163-CMC.ovpn
cat /var/www/html/CUC.ovpn >> /var/www/html/163-CUC.ovpn
cat /var/www/html/CTC.ovpn >> /var/www/html/163-CTC.ovpn
cat /var/www/html/CMC.ovpn >> /var/www/html/163-CMC.ovpn
done
