#!/bin/sh
mkdir /var/log/tinyproxy/ -p
echo "Start" >> /var/log/tinyproxy/tinyproxy.log
while true
do
aaa=0   
aaa=`cat /var/log/tinyproxy/tinyproxy.log | grep Interrupted | grep -v "grep"| wc -l |awk '{print $1}'`
if [ $aaa -ne 0 ] 
then    
rm -rf /var/log/tinyproxy/tinyproxy.log
pkill tinyproxy
service tinyproxy restart 
fi
ps -ef | grep "vpncmd 127.0.0.1:33394" | grep -v "grep" | awk '{print $2}' | xargs kill -s 9 > /dev/null 2>&1
/usr/sbin/VPNAnalyse &
sleep 15
done
