#!/bin/bash
IPAddress=`wget http://members.3322.org/dyndns/getip -O - -q ; echo`
if [ -f /opt/rootpasswd.log ];
then
 echo " "
 echo " "
 echo "===================== Restart ========================="
else
 echo "====================== Start =========================="
 echo "`date +%s | sha256sum | base64 | head -c 12`" > /opt/rootpasswd.log
 echo "root:`cat /opt/rootpasswd.log`" | chpasswd
 echo "serverpasswordset `cat /opt/rootpasswd.log` " >/opt/vpnserver/passwd.log
 echo "hub default " >>/opt/vpnserver/passwd.log
 echo "SetHubPassword `cat /opt/rootpasswd.log`" >>/opt/vpnserver/passwd.log
 echo "UserPasswordSet root /password:`cat /opt/rootpasswd.log` " >>/opt/vpnserver/passwd.log
 echo "exit" >>/opt/vpnserver/passwd.log
 echo "root:`cat /opt/rootpasswd.log`" | chpasswd
fi
#sleep 1
#service mproxy start >/dev/null 2>&1
sleep 1
service tinyproxy start
sleep 1
service httpd start >/dev/null 2>&1
sleep 1
service sshd start
sleep 1
/opt/vpnserver/vpnserver start
sleep 1
if [ -f /opt/vpnserver/passwd.log ];
then
 /opt/vpnserver/vpncmd 127.0.0.1:33394 /server /password:root /IN:/opt/vpnserver/passwd.log > /opt/vpnserver/changepasswd.log
 mv /opt/vpnserver/passwd.log /opt/vpnserver/passwd.bak
fi
echo Visit http://$IPAddress:8888 to Get More info!
echo "======================================================="
echo " "
echo "         PassWord : `cat /opt/rootpasswd.log`"
echo " "
echo "======================================================="
echo " "
echo "Made By alechy 2016-06-28"
echo "Do you have any quesions? To Jion QQ Group : 261167945"
echo "People who profit from the Image are immoral!"
echo "http-proxy $IPAddress 80" > /var/www/html/163-CUC.ovpn
echo "http-proxy $IPAddress 80" > /var/www/html/163-CTC.ovpn
echo "http-proxy $IPAddress 80" > /var/www/html/163-CMC.ovpn
cat /var/www/html/CUC.ovpn >> /var/www/html/163-CUC.ovpn
cat /var/www/html/CTC.ovpn >> /var/www/html/163-CTC.ovpn
cat /var/www/html/CMC.ovpn >> /var/www/html/163-CMC.ovpn
/usr/sbin/monitor &
wait
